#!/usr/bin/env python
# -*- coding: UTF-8 -*-
import os
from setuptools import setup

setup(
    name = 'my_paldea',
    version = '1.0',
    license='GNU General Public Licence v3',
    author='Gerves Baniakina',
    author_email='gerves-francois.baniakina@cgu.edu',
    description=' Personal Financial Budget Planning',
    packages=['my_paldea'],
    platforms='any',
    install_requires=[
        'Flask==3.1.2',
        'Flask-SQLAlchemy==3.1.1',
        'Flask-Login==0.6.3',
        'Flask-Bcrypt==1.0.1',
        'Flask-Migrate==4.1.0',
        'Flask-Dance==7.1.0',
        'Flask-WTF==1.2.2',
        'Authlib==1.6.5',
        'redis==6.4.0',
        'ldap3==2.9.1',
        'requests==2.32.5',
        'oauthlib==3.3.1',
        'requests-oauthlib==2.0.0',
        'URLObject==3.0.0',
        'WTForms==3.2.1',
        'alembic==1.17.0',
        'bcrypt==5.0.0',
        'blinker==1.9.0',
        'certifi==2025.10.5',
        'cffi==2.0.0',
        'charset-normalizer==3.4.4',
        'click==8.3.0',
        'colorama==0.4.6',
        'cryptography==46.0.3',
        'greenlet==3.2.4',
        'idna==3.11',
        'itsdangerous==2.2.0',
        'Jinja2==3.1.6',
        'Mako==1.3.10',
        'MarkupSafe==3.0.3',
        'pyasn1==0.6.1',
        'pycparser==2.23',
        'SQLAlchemy==2.0.44',
        'typing_extensions==4.15.0',
        'urllib3==2.5.0',
        'Werkzeug==3.1.3',
    ],
    classifiers=[
        'Development Status :: 4 -Beta',
        'Environment :: Web Environment',
        'Intended Audience :: Developers',
        'License :: OSI Approved :: GNU General Public License v3',
        'Operating System :: OS Independent',
        'Programming Language :: Python',
        'Topic :: Internet :: WWW/HTTP :: Dynamic Content',
        'Topic :: Software Development :: Libraries :: Python Modules'

    ],
)
